name: Release & Publish

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Update version if manually triggered
      if: github.event_name == 'workflow_dispatch'
      run: |
        VERSION=${{ github.event.inputs.version }}
        sed -i "s/version = '.*'/version = '$VERSION'/" build.gradle
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Release version $VERSION" -a || echo "No changes to commit"

    - name: Build plugin
      run: ./gradlew buildPlugin

    - name: Verify plugin
      run: ./gradlew runPluginVerifier

    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-generator-plugin
        path: build/distributions/*.zip

    - name: Publish Plugin to JetBrains Marketplace
      if: success()
      run: ./gradlew publishPlugin
      env:
        PUBLISH_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
        CHANGELOG: ${{ github.event.release.body }}

    - name: Create GitHub Release
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        name: Version ${{ github.event.inputs.version }}
        files: build/distributions/*.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
